---
author: "Thomas Parr & John Paul Schmit"
date: "2/05/2022"
output: 
  html_document:
    css: custom_styles.css
---
#### Functions Used Today
We want to provide you with a summary of functions and operators that we will be using in this section. We suggest using R help to read up on them before class. You don't have to master them, but be generally aware of them. You can use these help functions to look up the functions and operators below:
<ul>
  `help()` - searches help files for packages loaded into namespace<br>
  `?` - searches help files for packages loaded into namespace<br>
  `??` - searches all help files regardless of wether or not they are loaded<br>
</ul>

Base operators and things that look like them. When looking these up, they must be wrapped in `' '`
 <ul>
  `=`
  `<-`
  `==`
  `!`
  `!=`
  `>`
  `>=`
  `<`
  `<=`
  `%in%`
  `|`
  `&`
 </ul> 

base (and packages in base)
  <ul>
  `library()`
  `[]`
  `[[]]`
  `rm()`
  `function(){}`
  `data.frame`
  `file.path()`
  `format`
  `object.size()`
  `for(){}`
  `apply()`
  `tapply()`
  `sapply()`
  `lapply()`
  `do.call()`
  `rbind()`
  `names()`, `setNames()`, `colNames()`
  `nrow()`
  `rpois()`
  `quantile()`
  `plot()`
  `vector()`
  `read.csv()`
  `class()`
  `is.numeric()`
  `is.na()`
  `mean`
  `if(){}else{}`
  `return()`
  `glm()`
  `all()`
  `map_if()`
<<<<<<< HEAD
</ul>  
=======
  `paste0()`
  `length()`
  `c()`
  `boxplot()`
  
>>>>>>> 3971960fd8a0b7c964b82e5d3dc7c192a2b6b82d
dplyr
<ul>
  `%>%` and `.`
  `filter()`
  `mutate()`
  `case_when`
  `bind_rows()`
  `select()`
  `rename()`
  `date()`
  `group_by()`
  `across()`
  `summarize()`
  `pivot_longer()`
<<<<<<< HEAD
</ul> 
tidyselect
<ul>
  `where`
</ul>
=======
  
  
tidyselect
  `where()`
  `starts_with()`
  `any_of()`
  
>>>>>>> 3971960fd8a0b7c964b82e5d3dc7c192a2b6b82d
tidyr
<ul>
  `unite`
<<<<<<< HEAD
  `pivot_longer`
</ul>
=======
  `pivot_longer()`
  
>>>>>>> 3971960fd8a0b7c964b82e5d3dc7c192a2b6b82d
microbenchmark
<ul>
  `microbenchmark()`
</ul>  
ggplot2
<ul>
  `ggplot()`
  `geom_point()`
  `geom_line()`
  `facet_grid()`
  `ggsave()`
</ul>  
purrr
<<<<<<< HEAD
<ul>
  `map`
  `map2`
  `map_dbl`
  `discard()`
</ul>  
=======
  `set_names()`
  `map()`
  `map2()`
  `map_dbl()`
  `discard()`
  `map_if()`
  
>>>>>>> 3971960fd8a0b7c964b82e5d3dc7c192a2b6b82d
lubridate
<ul>
  `mdy()`
  `mdy_hms()`
</ul>
modelr
<<<<<<< HEAD
<ul>
  `add_predictions()`
</ul>
=======
  `add_predictions()`

readr
  `read_csv()`
  
profvis
  `profvis()`
>>>>>>> 3971960fd8a0b7c964b82e5d3dc7c192a2b6b82d
