---
output: 
  bookdown::html_document2:
    css: custom_styles.css
    numbered_sections: false
    number_sections: false
    fig_caption: true
title: "NPS IMD Advanced R Training"
---
<h2>NPS Inventory and Monitoring Division Advanced R Training: February 5 -- February 8, 2022</h2> {.tabset .tabset-pills}
--------------------------------------------------

### Prep for Training {.tabset}

```{r Install_instructions, child = "IMD_D0_Training_Prep.Rmd"}

```

### Day 1: Data Retrievel {.tabset}


### Day 2: Functional Programming {.tabset}

```{r FunctionsI, child = "D6_M1_Functions.Rmd", error = T}

```

```{r Iteration1, child = "IMD_D6_M2_Iteration.Rmd", error = T, eval = F}

```

### Day 3: R Markdown {.tabset}

```{r RmarkdownI, child = "IMD_D3_R_Markdown_I.Rmd"}

```

```{r RmarkdownII, child = "IMD_D3_R_Markdown_II.Rmd"}

```

### Day 4: Version Control {.tabset}
```{r VersionControl, child = "IMD_D4_Version_control_I.Rmd"}

```

### Day 4: R Packages {.tabset}

```{r RpackagesI, child = "IMD_D4_R_packages_I.Rmd"}

```

```{r RpackagesII, child = "IMD_D4_R_packages_II.Rmd"}

```

```{r RpackagesIII, child = "IMD_D4_R_packages_III.Rmd"}

```


### Code printout {.tabset}
```{r Code_printout, child = "IMD_Code_Printout.Rmd"}

```

### Meet the Instructors
```{r about, child = "IMD_Meet_the_Trainers.Rmd"}

```
